const $=id=>document.getElementById(id);
// Each pair is [fret, finger], ordered from low E to high E; -1 means muted.
const chords={C:{name:'Do',notes:[[-1,0],[3,3],[2,2],[0,0],[1,1],[0,0]]},D:{name:'Re',notes:[[-1,0],[-1,0],[0,0],[2,1],[3,3],[2,2]]},E:{name:'Mi',notes:[[0,0],[2,2],[2,3],[1,1],[0,0],[0,0]]},F:{name:'Fa',notes:[[1,1],[3,3],[3,4],[2,2],[1,1],[1,1]],barre:true},G:{name:'Sol',notes:[[3,2],[2,1],[0,0],[0,0],[0,0],[3,3]]},A:{name:'La',notes:[[-1,0],[0,0],[2,1],[2,2],[2,3],[0,0]]},Am:{name:'La menor',notes:[[-1,0],[0,0],[2,2],[2,3],[1,1],[0,0]]},Dm:{name:'Re menor',notes:[[-1,0],[-1,0],[0,0],[2,2],[3,3],[1,1]]},Em:{name:'Mi menor',notes:[[0,0],[2,2],[2,3],[0,0],[0,0],[0,0]]}};
let mode='learn';
let sequence=['G','D','Em','C'], index=0, running=false, origin=0, beatIndex=-1, raf, context, errors=[],stream, micFrame, source;
const period=()=>60/Number($('bpm').value);
function diagram(key){const c=chords[key];let s='<svg viewBox="0 0 230 235" role="img" aria-label="'+c.name+': '+c.notes.map(([f,d],i)=>`cuerda ${6-i}, ${f<0?'no tocar':f===0?'al aire':`traste ${f}, dedo ${d}`}`).join('; ')+(c.barre?'; cejilla con índice en traste 1':'')+'">';for(let f=0;f<=4;f++)s+=`<line x1="40" y1="${42+f*36}" x2="190" y2="${42+f*36}" stroke="#b9c4ab" stroke-width="${f===0?4:1}"/>`;for(let i=0;i<6;i++)s+=`<line x1="${40+i*30}" y1="42" x2="${40+i*30}" y2="186" stroke="#899b7f" stroke-width="${1.6-i*.15}"/><text x="${40+i*30}" y="211" text-anchor="middle" fill="#89957e" font-size="10">${['Mi','La','Re','Sol','Si','Mi'][i]}</text>`;if(c.barre)s+='<rect x="29" y="49" width="172" height="23" rx="11" fill="#426645"/>';c.notes.forEach(([f,d],i)=>{let x=40+i*30;if(f<=0)s+=`<text x="${x}" y="27" text-anchor="middle" font-size="17" fill="#819271">${f===0?'○':'×'}</text>`;else s+=`<circle cx="${x}" cy="${24+f*36}" r="12" fill="#345d3e"/><text x="${x}" y="${28+f*36}" text-anchor="middle" fill="white" font-size="11" font-weight="600">${d}</text>`});return s+'</svg>'}
function render(){const current=sequence[index],next=sequence[(index+1)%sequence.length];$('chordName').textContent=chords[current].name;$('chordSymbol').textContent=current;$('diagram').innerHTML=diagram(current);$('chordHint').textContent=chords[current].barre?'Cejilla: el índice presiona las seis cuerdas en el primer traste.':'Los números indican qué dedo usar.';$('nextName').textContent=chords[next].name;$('nextSymbol').textContent=next;$('nextDiagram').innerHTML=diagram(next);$('position').textContent=`COMPÁS ${index+1} / ${sequence.length}`;$('timeline').replaceChildren(...sequence.map((c,i)=>{let b=document.createElement('button');b.className=i===index?'selected':'';b.innerHTML=`<small>${String(i+1).padStart(2,'0')}</small><strong>${c}</strong><span>${chords[c].name}</span>`;b.onclick=()=>{stop();index=i;render()};return b}));}
function drawBeat(n){$('beats').innerHTML=[0,1,2,3].map(i=>`<span class="beat ${i===n?'active':''}">${i+1}</span>`).join('')}
async function audio(){context??=new AudioContext();await context.resume()}
function tick(accent){if(!$('click').checked||!context)return;let o=context.createOscillator(),g=context.createGain();o.frequency.value=accent?1000:720;g.gain.setValueAtTime(.12,context.currentTime);g.gain.exponentialRampToValueAtTime(.001,context.currentTime+.05);o.connect(g).connect(context.destination);o.start();o.stop(context.currentTime+.06)}
function frame(){if(!running||mode==='learn')return;const b=Math.floor((performance.now()/1000-origin)/period());if(b!==beatIndex){if(beatIndex>=0){const crossed=Math.floor(b/4)-Math.floor(beatIndex/4);if(crossed){index=(index+crossed)%sequence.length;render()}}beatIndex=b;drawBeat(b%4);tick(b%4===0)}raf=requestAnimationFrame(frame)}
function stop(){running=false;cancelAnimationFrame(raf);$('play').textContent='▶ Empezar práctica';$('status').textContent='En pausa';drawBeat(-1)}
$('play').onclick=async()=>{if(running){stop();return}try{await audio()}catch{}running=true;origin=performance.now()/1000;beatIndex=-1;$('play').textContent='Ⅱ Pausar';$('status').textContent=mode==='learn'?'Esperando tu acorde…':'Seguí el pulso · 4 tiempos';if(mode==='rhythm')frame()};
$('restart').onclick=()=>{stop();index=0;errors=[];$('score').textContent='—';$('feedback').textContent='Empezá la práctica y marcá cada rasgueo.';render()};
function setTempo(value){$('bpm').value=Math.max(40,Math.min(200,Math.round(Number(value)||80)));if(running){origin=performance.now()/1000;beatIndex=-1}}
$('bpm').onchange=e=>setTempo(e.target.value);$('slower').onclick=()=>setTempo(Number($('bpm').value)-5);$('faster').onclick=()=>setTempo(Number($('bpm').value)+5);
$('song').onchange=()=>{$('customBox').hidden=$('song').value!=='custom';if($('song').value==='custom')return;stop();sequence=$('song').value==='intro'?['G','D','Em','C']:['Am','F','C','G'];index=0;render()};
$('apply').onclick=()=>{let list=$('custom').value.trim().split(/[\s,–-]+/);let invalid=list.filter(c=>!Object.hasOwn(chords,c));if(invalid.length||list.length>64){$('customError').textContent='Usá de 1 a 64 acordes de la lista: C D E F G A Am Dm Em.';return}$('customError').textContent='';stop();sequence=list;index=0;render()};
function tap(){if(mode==='learn'){ $('feedback').textContent='En este modo el micrófono busca el acorde indicado. También podés avanzar con Siguiente acorde.';return}if(!running){$('feedback').textContent='Primero empezá la práctica para medir tu ritmo.';return}let elapsed=performance.now()/1000-origin;let delta=(elapsed-Math.round(elapsed/period())*period())*1000;errors.push(Math.abs(delta));if(errors.length>32)errors.shift();$('score').textContent=Math.round(errors.reduce((a,b)=>a+b,0)/errors.length)+' ms';$('feedback').textContent=Math.abs(delta)<65?'¡A tiempo! Seguí así.':`${Math.round(Math.abs(delta))} ms ${delta<0?'adelantado':'atrasado'} · Escuchá el próximo pulso.`}
$('tap').onclick=tap;document.addEventListener('keydown',e=>{if(e.code==='Space'&&!['INPUT','SELECT','TEXTAREA','BUTTON'].includes(e.target.tagName)){e.preventDefault();if(!e.repeat)tap()}});
function stopMic(){cancelAnimationFrame(micFrame);stream?.getTracks().forEach(t=>t.stop());source?.disconnect();stream=null;$('mic').textContent='♩ Activar micrófono';$('micStatus').textContent='Micrófono apagado.'}
$('mic').onclick=async()=>{if(stream){stopMic();return}if(!navigator.mediaDevices?.getUserMedia){$('micStatus').textContent='El micrófono necesita abrir la app desde localhost o HTTPS.';return}$('mic').disabled=true;try{await audio();stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}});source=context.createMediaStreamSource(stream);let analyser=context.createAnalyser();analyser.fftSize=8192;source.connect(analyser);let data=new Float32Array(analyser.fftSize),spectrum=new Float32Array(analyser.frequencyBinCount),lastRecognition=0,matchingSince=0,cooldown=0,baseline=.005,previous=0,last=0;function listen(){analyser.getFloatTimeDomainData(data);let rms=Math.sqrt(data.reduce((s,x)=>s+x*x,0)/data.length),now=performance.now();if(rms>Math.max(.018,baseline*2.1)&&rms>previous*1.25&&now-last>180){if(running&&mode==='rhythm')tap();last=now}if(running&&mode==='learn'&&now-lastRecognition>110&&now>cooldown){
lastRecognition=now;
if(rms>.012){
analyser.getFloatFrequencyData(spectrum);
const detected=recognize(spectrum,context.sampleRate,analyser.fftSize,sequence[index]);
if(detected){if(!matchingSince)matchingSince=now;if(now-matchingSince>550){const name=chords[sequence[index]].name;index=(index+1)%sequence.length;render();$('feedback').textContent=name+' detectado. Prepará '+chords[sequence[index]].name+'.';$('status').textContent='¡Bien! Cambiá la mano';matchingSince=0;cooldown=now+1500}}else{matchingSince=0;$('status').textContent='Escuchando: '+chords[sequence[index]].name}
}else matchingSince=0;
}
baseline=baseline*.97+rms*.03;previous=rms;micFrame=requestAnimationFrame(listen)}listen();$('mic').textContent='■ Apagar micrófono';$('micStatus').textContent='Micrófono activo · Reconocimiento experimental. Tocá todas las cuerdas indicadas y dejá sonar.'}catch(e){stopMic();$('micStatus').textContent=e.name==='NotAllowedError'?'Permiso de micrófono denegado. Podés marcar los rasgueos con el botón.':'No se pudo abrir el micrófono. Revisá el dispositivo.'}finally{$('mic').disabled=false}};
document.addEventListener('visibilitychange',()=>{if(document.hidden&&running)stop()});window.addEventListener('pagehide',stopMic);render();drawBeat(-1);

const pitchClasses={C:[0,4,7],D:[2,6,9],E:[4,8,11],F:[5,9,0],G:[7,11,2],A:[9,1,4],Am:[9,0,4],Dm:[2,5,9],Em:[4,7,11]};
function recognize(spectrum,sampleRate,fftSize,target){
 const chroma=Array(12).fill(0);
 // Local spectral peaks reduce leakage; notes are pooled across octaves.
 for(let i=2;i<spectrum.length-1;i++){
  const hz=i*sampleRate/fftSize;
  if(hz<75||hz>1300||spectrum[i]<-65||spectrum[i]<spectrum[i-1]||spectrum[i]<spectrum[i+1])continue;
  const midi=69+12*Math.log2(hz/440),nearest=Math.round(midi);
  if(Math.abs(midi-nearest)>.32)continue;
  chroma[(nearest%12+12)%12]+=Math.pow(10,spectrum[i]/20)/Math.sqrt(hz/80);
 }
 const total=chroma.reduce((a,b)=>a+b,0);if(total<.001)return false;
 const ranked=Object.entries(pitchClasses).map(([key,pcs])=>({key,coverage:pcs.reduce((s,p)=>s+chroma[p],0)/total,min:Math.min(...pcs.map(p=>chroma[p]/total))})).sort((a,b)=>b.coverage-a.coverage);
 return ranked[0].key===target&&ranked[0].coverage>.72&&ranked[0].min>.07&&ranked[0].coverage-ranked[1].coverage>.08;
}
function setMode(next){stop();mode=next;errors=[];$('score').textContent='—';$('learnMode').classList.toggle('selected',mode==='learn');$('rhythmMode').classList.toggle('selected',mode==='rhythm');$('modeHelp').textContent=mode==='learn'?'El acorde espera por vos. Activá el micrófono y tocá el acorde indicado para avanzar.':'Seguí los cuatro pulsos de cada acorde. Bajá la velocidad para practicar los cambios.';$('nextManual').hidden=mode!=='learn';$('tap').hidden=mode==='learn';$('feedback').textContent=mode==='learn'?'Activá el micrófono y empezá. El reconocimiento de acordes es experimental.':'Empezá y marcá los rasgueos o usá el micrófono.';document.querySelector('.score').hidden=mode==='learn';$('click').disabled=mode==='learn';document.querySelector('.beat-row').hidden=mode==='learn';document.querySelector('.section-heading span').textContent=mode==='learn'?'Avanzá al reconocer el acorde · Sin límite de tiempo':'4 pulsos por acorde · Repetición continua';document.querySelector('.rhythm h3').textContent=mode==='learn'?'Escuchamos tu acorde':'¿Cómo venís de ritmo?';document.querySelector('.rhythm .muted').textContent=mode==='learn'?'Tocá el acorde completo y dejalo sonar. La detección puede equivocarse.':'La medición compara tus ataques con el pulso. No verifica las notas del acorde.';$('status').textContent='Listo cuando vos estés'}
$('learnMode').onclick=()=>setMode('learn');$('rhythmMode').onclick=()=>setMode('rhythm');$('nextManual').onclick=()=>{index=(index+1)%sequence.length;render()};setMode('learn');
